import { Conversation } from "../models/conversation.model.js";
import { Message } from "../models/message.model.js";

/**
 * ConversationService — Repository layer for Conversation operations.
 * Public API always uses UUID. ObjectId is never exposed externally.
 */

/**
 * Create a new conversation for a user.
 * UUID is auto-generated by the model default.
 * @param {string} userId 
 * @param {string} title 
 * @param {import('mongoose').ClientSession} [session]
 */
export const createConversation = async (userId, title, session = null) => {
    const opts = session ? { session } : {};
    const conversation = await Conversation.create([{ userId, title }], opts);
    return conversation[0];
};

/**
 * List all conversations for a user, sorted by most recently updated.
 * @param {string} userId 
 */
export const listConversations = async (userId) => {
    return Conversation.find({ userId })
        .sort({ updatedAt: -1 })
        .select('-__v')
        .lean();
};

/**
 * Get a single conversation by PUBLIC UUID, ensuring it belongs to the user.
 * @param {string} uuid 
 * @param {string} userId 
 */
export const getConversationByUUID = async (uuid, userId) => {
    return Conversation.findOne({ uuid, userId }).lean();
};

/**
 * Get a single conversation by internal MongoDB ObjectId.
 * Used ONLY for internal service-to-service operations.
 * @param {string} id  — MongoDB ObjectId string
 * @param {string} userId 
 */
export const getConversationById = async (id, userId) => {
    return Conversation.findOne({ _id: id, userId }).lean();
};

/**
 * Rename a conversation. Verifies ownership via UUID.
 * @param {string} uuid 
 * @param {string} userId 
 * @param {string} title 
 */
export const renameConversation = async (uuid, userId, title) => {
    return Conversation.findOneAndUpdate(
        { uuid, userId },
        { title: title.trim(), updatedAt: new Date() },
        { new: true }
    ).lean();
};

/**
 * Delete a conversation and all its messages atomically.
 * Looks up by UUID; uses internal ObjectId for cascade delete.
 * @param {string} uuid 
 * @param {string} userId 
 */
export const deleteConversation = async (uuid, userId) => {
    const session = await Conversation.startSession();
    try {
        session.startTransaction();

        const conversation = await Conversation.findOneAndDelete(
            { uuid, userId },
            { session }
        );
        if (!conversation) {
            await session.abortTransaction();
            return null;
        }

        // Cascade delete messages using the internal ObjectId
        await Message.deleteMany({ conversationId: conversation._id }, { session });
        await session.commitTransaction();
        return conversation;
    } catch (err) {
        await session.abortTransaction();
        throw err;
    } finally {
        session.endSession();
    }
};

/**
 * Bump conversation's updatedAt to move it to the top of the list.
 * @param {string} id  — internal ObjectId
 * @param {import('mongoose').ClientSession} [session]
 */
export const touchConversation = async (id, session = null) => {
    const opts = session ? { session } : {};
    return Conversation.findByIdAndUpdate(
        id,
        { updatedAt: new Date() },
        { new: true, ...opts }
    );
};

/**
 * Resolve a public UUID to an internal ObjectId string.
 * Used by internal endpoints so the Agent Service stays storage-agnostic.
 * @param {string} uuid
 * @returns {string|null} ObjectId string or null if not found
 */
export const resolveUUIDToObjectId = async (uuid) => {
    const conv = await Conversation.findOne({ uuid }).select('_id').lean();
    return conv ? conv._id.toString() : null;
};
